/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizPhaseIdRouteImport } from './routes/quiz.$phaseId'
import { Route as LessonPhaseIdModuleIdRouteImport } from './routes/lesson.$phaseId.$moduleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPhaseIdRoute = QuizPhaseIdRouteImport.update({
  id: '/quiz/$phaseId',
  path: '/quiz/$phaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonPhaseIdModuleIdRoute = LessonPhaseIdModuleIdRouteImport.update({
  id: '/lesson/$phaseId/$moduleId',
  path: '/lesson/$phaseId/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/quiz/$phaseId': typeof QuizPhaseIdRoute
  '/lesson/$phaseId/$moduleId': typeof LessonPhaseIdModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/quiz/$phaseId': typeof QuizPhaseIdRoute
  '/lesson/$phaseId/$moduleId': typeof LessonPhaseIdModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/quiz/$phaseId': typeof QuizPhaseIdRoute
  '/lesson/$phaseId/$moduleId': typeof LessonPhaseIdModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/quiz/$phaseId'
    | '/lesson/$phaseId/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/quiz/$phaseId'
    | '/lesson/$phaseId/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/quiz/$phaseId'
    | '/lesson/$phaseId/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  QuizPhaseIdRoute: typeof QuizPhaseIdRoute
  LessonPhaseIdModuleIdRoute: typeof LessonPhaseIdModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$phaseId': {
      id: '/quiz/$phaseId'
      path: '/quiz/$phaseId'
      fullPath: '/quiz/$phaseId'
      preLoaderRoute: typeof QuizPhaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$phaseId/$moduleId': {
      id: '/lesson/$phaseId/$moduleId'
      path: '/lesson/$phaseId/$moduleId'
      fullPath: '/lesson/$phaseId/$moduleId'
      preLoaderRoute: typeof LessonPhaseIdModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  QuizPhaseIdRoute: QuizPhaseIdRoute,
  LessonPhaseIdModuleIdRoute: LessonPhaseIdModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
